<?php

/**
 * @file
 * Session keep-alive for Shibboleth IPD by creating a persistent cookie out of the shibboleth ones
 * and forwarding the user to the login url to re-create the proper authentication cookies.
 * Also stores the app server cookie so the same load balancer is hit by the request, making sure
 * that the same shibboleth instance generates the cookies.
 */

/**
 * Implements hook_init().
 */
function shib_auth_keepalive_init() {
  if (user_is_anonymous() && !isset($_COOKIES['shib_auth_keepalive_stored']) && isset($_COOKIES['shib_auth_keepalive_session'])) {
    setcookie($_COOKIES['shib_auth_keepalive_session_key'], $_COOKIES['shib_auth_keepalive_session_value']);
    setcookie('ah_app_server', $_COOKIES['shib_auth_keepalive_ah_app_server']);  

    // Now redirect to the SSO url.
    drupal_goto(shib_auth_config('login_url'));
  }
}

/**
 * Implements hook_exit().
 * Create a persistent cookie out of the ones
 */
function shib_auth_keepalive_exit() {

  if (!user_is_anonymous() && !isset($_COOKIE['shib_auth_keepalive_stored'])) {
    setcookie('shib_auth_keepalive_stored', TRUE);
    if (!empty($_COOKIES)) {
      foreach($_COOKIES as $key => $value) {
        if (substr($key, 0, 13) == '_shibsesssion_') {
          setcookie('shib_auth_keepalive_session_key', $key);
          setcookie('shib_auth_keepalive_session_value', $value);
          setcookie('shib_auth_keepalive_ah_app_server', $_COOKIES['ah_app_server']);
        }
      }  
    }
  }
}

/**
 * Implements hook_user().
 * Make sure to destroy the keep-alive cookies when the user logs out.
 */
function shib_auth_keepalive_user_logout( &$edit, &$account) {
	setcookie($_COOKIES['shib_auth_keepalive_session_key'], '', time() - 3600);
	setcookie($_COOKIES['shib_auth_keepalive_session_value'], '', time() - 3600);
	setcookie($_COOKIES['shib_auth_keepalive_ah_app_server'], '', time() - 3600);
}
